spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://fxmaoyuzzz:3306/test
    username: root
    password: root
  data:
    mongodb:
      database:
      uri: mongodb://47.117.142.234:27017/test?authSource=admin